### PR TITLE
#minor Re-structured package functions around `call_` and `compare_` family of functions

### LINKED ISSUE #243: Dataset by dataset comparison function
Add an extension to db_comp() that allows to compare two datasets at a time for the categories coded.

### LINKED ISSUE #248: Better visualisations for agreements/memberships data
With the recent addition of the network map functions, manydata should also include some default functions to plot 'many' data.

### LINKED ISSUE #249: Possible updates to db_plot() to include new features/categories
- Add percentages to columns
- Remove Beg and End variables (for all)
- Code conflicts into recognised conflit and unrecognised conflict

### LINKED ISSUE #250: Numeric selection in get_packages() incorrect
Because no 'manyhealth' expected, manypkgs, manystates, and manytrade all need to be increased by 1 integer. Alternatively (and safer), this should be a look up.

### LINKED ISSUE #251: Need to install (update) multiple packages at once
To save time, need to be able to pass `get_packages()` a vector of package names, numbers from the table, or choose (as an argument or another function) `update_all` to update all those packages that have an installed version number behind the latest available version number.

### LINKED ISSUE #253: Fix bug with `db_plot()` when "internal = TRUE" argument is used
Since we have changed the location of verified/checked data and variable in the data packages, the function cannot find the "checked" column used for differentiating conflicts for internal use...

### LINKED ISSUE #259: Revise CCC structure for manydata
The collect, correct, and connect (CCC) structure of manydata is not appropriate anymore. This is reflective of a time when manydata and manypkgs were one package.

One alternative is to frame the PANARCHIC project, as a whole, in regards to a CCC structure. The "collect" portion could relate to the data packages, the correct/code portion could be reflective of manypkgs, and the connect/consolidate portion could relate to manydata.

In any case, the cheatsheet for manydata should change...

### LINKED ISSUE #261: Raname/recode 'db' functions to compare family of functions
Current options:

- `compare_categories()` instead of db_comp() with a method for plotting (e.g. `plot(compare_categories()` that substitutes db_plot())
- `compare_missing()` instead of db_heatmap() with a method for plotting (e.g. `plot(compare_missing()` that substitutes db_heatmap())
- `compare_data()` instead of `data_contrast()`

### LINKED ISSUE #264: Revisit dependencies for manydata
There are currently too many dependencies. Take a look especially at the dependencies related to `plot_releases()` (maybe work with NEWS files instead of GitHub if we can add date) and dependencies related to plotting functions that could be moved elsewhere.

### LINKED ISSUE #268: Create a VEM diagram for plotting dataset overlaps
Maybe this would be a plot for something like a `compare_ overlap(database, key, variables)` function that returns a matrix structure with overlaps...

### LINKED ISSUE #269: Create a get or a call source function
For `get_source()`:

- Add description column about each dataset 
- Add URL for HUGGO and AIGGO (maybe panarchic.ch) - also can we make it clickable see issue #267
- Maybe add a separate codebook variable for codebook, since we are removing `open_codebook()`
- Create a new variable called "Variable mapping" for the columns that have changed names and how, since we are removing `data_evolution()` (this might require we save an internal data file with this info that we can quickly get it without going through GitHub)

### LINKED ISSUE #271: Rename `retrive_` functions to call or get family

### LINKED ISSUE #276: Review vignette and tests for new changes in manydata
With the many changes in manydata, both the vignette and tests need to be revised, added and reworked.

### LINKED ISSUE #277: Update manydata-defunct script
Now that many functions have been renamed and/or updated, we need to properly complete the manydata-defunct script so that users now where to look for in case they use old function names. Thank you!

### LINKED ISSUE #283: Make `plot_releases()` a `call_` function that returns a tibble but can be plotted (i.e. `plot(call_releases("manydata))`)

### LINKED ISSUE #284: Review README file and vignette to make it consistent and add missing information

### LINKED ISSUE #285: Separate `compare_data()` into `compare_dimensions()` and `compare_ranges()`
- `compare_dimensions(database, dataset = "all")` - observations and variable names

- `compare_ranges(database, dataset = "all", variable)` - ranges min/max/mean/median for a specific variable

### PR DESCRIPTION
**Pull request by henriquesposito**
# Description

This minor PR re-structured package functions around the `call_` and `compare_` family of functions.

## Package

* Closed #259 by revising CCC package structure and updating the package cheatsheet
* Updated documentation for 'emperors' data to new style to improve visibility and transparency
* Closed #264 by removing `{tibble}`and `{janitor}` package imports in DESCRIPTION file
* Closed #276 by reviewing package vignettes
* Closed #277 by updating 'manydata-defunct' file
* Closed #284 by removing vignette and updating README to include more information on how to use the package
* Updated all references and argument from 'database' to 'datacube'

## Connection

* Renamed and updated 'call_' family of functions
  * Closed #250, #251, and #262 by renaming `get_packages()` to `call_packages()` and updating how the function works and look up packages, version updates, and availailabity
  * Closed #269 and # by adding a `call_sources()` function that displays sources and variable changes for datasets in datacubes 
  * Closed #271 by updating the `retrieve_` family of functions to `call_` functions
  * Closed #283 by renaming `plot_releases()` to `call_releases`
* Renamed and updated 'compare_' family of functions
  * Closed #243 and #257 by creating a `compare_missing()` function to compare missing values in datasets in a 'many' datacube
  * Closed #249 and  #253 by renaming `db_plot()` function to `compare_categories()` and updating variable categories
  * Closed #261 by renaming and updating other `db_` functions to `compare_` functions
  * Closed #268 by adding `compare_overlap()` to help users investigate overlap for datasets within datacubes
  * Closed #285 by adding `compare_dimensions()` and `compare_ranges()` to compare dimensions and ranges in datacubes

# Checklist:

- [x] PR form
  - [x] I have given this pull request an informative title
  - [x] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [x] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [x] Package builds on my OS without issues
- [x] PR checks all pass for latest commit
  - [x] Package builds on Mac
  - [x] Package builds on Windows
  - [x] Package builds on Linux
  - [x] CodeCov check: Package improves or maintains good test coverage
  - [x] CodeFactor check: Package improves or maintains good style
- [x] Documentation
  - [x] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [x] Any longer functions are commented inline so that it is easier to debug in the future
  - [x] PR description above and the NEWS.md file are aligned
  - [x] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

### CODE REVIEW

**Comment by henriquesposito** [comment]
@jaeltan besides the vignette and reviewing/adding tests (issue #276) as well as updating manydata-defunct script (issue #277), I am taking note here of a few other things I would like you to please take a look at when going through the PR:

- Could you please take a look at the `call_sources()` outputs and tests? The function returns a 'tibble' but I am not sure the printing is ideal... either we have to make sure printing is better or we might want to default to base R printing (as we do in `messydates::mreport()`)... Also, tests appear not to work so they have been commented out. Notice that this function requires a completely new documentation style (see the 'emperors' documentation file in manydata). I have also commented in the respective issue.
- Could you please review the dependencies and see if we can move anything else to suggests (take a look at how we do this in the `plot_overlap()`for example)?
- Could you please take a look at why the PR checks appear not to be running?
- Could you please take a look at the merge conflicts (this is caused because we merged a feature branch today to fix a CRAN related issue with the package dependencies)?

Thank you so much in advance for all your help!

File: R/agreements_plot.R [hunk 1]
```diff
@@ -0,0 +1,285 @@
+#' Plot agreements network
+#' 
+#' @description Facilitates plotting of 'many' data.
+#' @param dataset A dataset from one of the many packages
+#' or a "consolidated" database.
+#' @param actor An actor variable.
+#' "StateID", by default.
+#' @param treaty_type The type of treaties to be returned.
+#' NULL, by default.
+#' Other options are "bilateral" or "multilateral".
```
Comment (jaeltan) [inline R/agreements_plot.R:10]: This didn't seem to work when I tried it

File: R/agreements_plot.R [hunk 2]
```diff
@@ -0,0 +1,285 @@
+#' Plot agreements network
+#' 
+#' @description Facilitates plotting of 'many' data.
+#' @param dataset A dataset from one of the many packages
+#' or a "consolidated" database.
```
Comment (jaeltan) [inline R/agreements_plot.R:5]: I removed the line 'Other options are "bilateral" or "multilateral".' since it didn't seem to fit in here

File: vignettes/user.Rmd [hunk 3]
```diff
@@ -21,44 +21,54 @@ Since some of these data packages are too big for CRAN,
 we expect that their developers will instead choose
```
Comment (jaeltan) [inline vignettes/user.Rmd:21]: I'm not sure what this sentence is supposed to convey to users about the many packages?

File: R/call.R [hunk 4]
```diff
@@ -0,0 +1,377 @@
...
+#' Please declare package, database, and dataset
+#' @importFrom utils help browseURL
+#' @importFrom dplyr relocate
+#' @importFrom stringr str_extract_all str_remove_all str_trim
+#' @export
+call_sources <- function(package, database, dataset = NULL,
+                         open_script = FALSE, open_codebook = FALSE) {
+  Dataset <- Source <- URL <- Mapping <- NULL
+  # get path
+  helptext <- utils::help(topic = as.character(database),
```
Comment (jaeltan) [inline R/call.R:212]: Just a note, I've uncommented the test for call_sources() because it now passes, but there were a few times where it didn't when I was running it on my end and the failure was because utils::help() couldn't pick up the path for the 'emperors' help file.

**Review by jaeltan — COMMENTED** [review]
Thanks @henriquesposito for all the hard work on manydata! I've added the functions to manydata-defunct.R, added a few tests, and updated the vignette and README, hope this helps. Please also let me know when you've finalised everything then I can update the cheatsheet.

File: R/call.R (hunk 4 above)
Comment (henriquesposito) [reply R/call.R:212]: Thank you @jaeltan !

**Review by jaeltan — APPROVED** [review]
Some very minor comments, thanks @henriquesposito !

File: R/compare.R [hunk 5]
```diff
@@ -0,0 +1,397 @@
...
+#'
+#' @description
+#' The `compare_` functions in `{manydata}` allows users to quickly compare
+#' different information on databases and/or datasets across 'many packages'.
+#' These include comparison for:
+#' - data summaries
+#' - missing observations
+#' - categories
+#' Each of these functions is accompanied by an appropriate printing method that
+#' allows users to visualize the comparisons.
```
Comment (jhollway) [inline R/compare.R:11]: There is an awful lot of different functions on this page too. Again, perhaps more separate documentation, and we can always connect the pages where helpful by using `@family`.

File: vignettes/user.Rmd [hunk 6]
```diff
@@ -17,48 +17,57 @@ library(manydata)
...
-It enables to point out the recurrence, 
-difference or absence of observations between the datasets and extract
-more robust data when researching on a particular governance domain. 
+principles across the different packages.
+
+For instance, in the data packages on international agreements
+(including `{manyenviron}`, `{manytrade}`, and `{manyhealth}`),
+the `agreements` and `memberships` databases have standardised date variables
+`Begin`, `Signature`, `Force`, and `End` that contain the beginning,
+signature, entry into force, and end dates of treaties respectively.
```
Comment (jhollway) [inline vignettes/user.Rmd:53]: Maybe keep Begin and End separate from Signature, Force, and End to make this clearer?

File: vignettes/user.Rmd [hunk 7]
```diff
@@ -17,48 +17,57 @@ library(manydata)
...
-get_packages()
+call_packages() # returns list of many packages
+```
+
+The `call_sources()` function can be used to view the sources, URLs,
+and variable changes for the datasets within a database within a many package.
+
+```{r source}
+call_sources(package = "manydata", database = "emperors")
 ```
```
Comment (jhollway) [inline vignettes/user.Rmd:40]: Could add quite a bit of this to the README? What's the advantage of having it in a vignette?

File: vignettes/user.Rmd [hunk 8]
```diff
@@ -88,47 +97,63 @@ relating to the same phenomenon are presented together.
...
+plot_overlap(emperors, key = "ID")
+```
+
+The `compare_missing()` function returns a tibble with the number and percentage of missing observations in datasets within database.
+This can also be visualized with the `plot_missing()` function.
+
+```{r missing}
+compare_missing(emperors)
+plot_missing(emperors)
 ```
```
Comment (jhollway) [inline vignettes/user.Rmd:143]: Why don't we just make `plot()` methods for the (S3 objects) returned by the `compare_*()` functions?

**Review by jhollway — DISMISSED** [review]

File: vignettes/user.Rmd (hunk 7 above)
Comment (henriquesposito) [reply vignettes/user.Rmd:40]: I agree, the README is a better place for this for being more visible! I added some of these to the README, I wonder if we should delete the vignette now?

File: pkgdown/_pkgdown.yml [hunk 9]
```diff
@@ -52,16 +52,16 @@ navbar:
         - text: manytrade
           href: https://globalgov.github.io/manytrade/
 reference:
-  - title: "Downloading 'many* packages' and inspecting data"
+  - title: "Calling 'many* packages' and inspecting data"
```
[the remark this answers is not in the document]
Comment (henriquesposito) [reply pkgdown/_pkgdown.yml:55]: Good catch! This has been updated for consistency and clarity

File: R/call.R [hunk 10]
```diff
@@ -0,0 +1,377 @@
...
+  lazyLoadDBexec(RdDB, fetchRdDB)
+}
+
+#' @describeIn call_ Call treaties from 'many' datasets
+#' @details Certain datasets, or consolidated databases, in 'many' packages
+#' contains information on treaties which can be retrieved
+#' with `call_treaties()`.
+#' @export
+call_treaties <- function(dataset, treaty_type = NULL,
+                          variable = NULL, actor = NULL) {
```
[the remark this answers is not in the document]
Comment (henriquesposito) [reply R/call.R]: Perhaps it could be, I am not sure. Another option would be to move it to `{manypkgs}` if that makes more sense. 

I wonder as well if `plot_releases()` should perhaps become `call_releases()`?

File: DESCRIPTION [hunk 11]
```diff
@@ -50,19 +50,16 @@ Imports:
     janitor,
     tidyr,
     plyr,
-    zoo
+    zoo,
+    igraph,
+    ggVennDiagram
```
[the remark this answers is not in the document]
Comment (henriquesposito) [reply DESCRIPTION]: If we decide to move ahead with `manygraph()` then yes, that could be a nice option. Another alternative is moving some of the specific plotting functions for agreements to either `manynet()` or `manypkgs()` for now.

File: vignettes/user.Rmd (hunk 7 above)
Comment (henriquesposito) [reply vignettes/user.Rmd:40]: I agree, perhaps either we have a more detailed vignette or we focus on the README and delete the vignette.

File: R/call.R [hunk 12]
```diff
@@ -0,0 +1,377 @@
...
+#' "Convention Between Roumania And Russia Concerning Fishing
+#' In The Danube And The Pruth",
+#' "Convention Between The Governments Of Denmark And
+#' The United Kingdom Of Great Britain
+#' And Northern Ireland For Regulating The Fisheries
+#' Of Their Respective Subjects Outside
+#' Territorial Waters In The Ocean Surrounding The Faroe Islands"),
+#' Begin = c("1901-02-22", "1901-02-22", "1901-06-24"))
+#' call_treaties(membs)
+#' call_treaties(membs, treaty_type = "bilaterals",
```
Comment (jaeltan) [inline R/call.R:325]: extra 's' in `treaty_type = "bilaterals"`?

File: R/call.R [hunk 13]
```diff
@@ -0,0 +1,377 @@
...
+#' variable = c("Title", "Begin"))
+#' call_treaties(membs, variable = c("Title", "Begin"), actor = "StateID")
```
Comment (jaeltan) [inline R/call.R:327]: I think the 's' in stateID is not capitalised

File: R/plot.R [hunk 14]
```diff
@@ -0,0 +1,277 @@
+#' Plot agreements network
+#' 
+#' @description Facilitates plotting of 'many' data.
+#' @param dataset A dataset from one of the many packages
+#' or a "consolidated" database.
+#' @param actor An actor variable.
+#' "StateID", by default.
```
Comment (jaeltan) [inline R/plot.R:7]: should be lower 's' in stateID

File: R/plot.R [hunk 15]
```diff
@@ -0,0 +1,277 @@
...
+NULL
+
+#' @rdname plot_
+#' @importFrom dplyr %>% select mutate distinct rename
+#' @importFrom manynet as_igraph autographr
+#' @return A network of agreements' relations.
+#' @examples
+#' \donttest{
+#' #agreements <- dplyr::filter(manyenviron::agreements$ECOLEX,
+#' #Beg > "2000-01-01" & Beg < "2000-12-12")
```
Comment (jaeltan) [inline R/plot.R:26]: Begin instead of Beg

File: R/plot.R [hunk 16]
```diff
@@ -0,0 +1,277 @@
...
+}
+
+#' @rdname plot_
+#' @importFrom dplyr %>% select distinct all_of rename
+#' @importFrom manynet as_igraph autographr
+#' @return A network of agreements' memberships.
+#' @examples
+#' \donttest{
+#' #memberships <- dplyr::filter(manyenviron::memberships$ECOLEX_MEM,
+#' #Beg > "2000-01-01" & Beg < "2000-01-31")
```
Comment (jaeltan) [inline R/plot.R:66]: Begin instead of Beg

File: R/plot.R [hunk 17]
```diff
@@ -0,0 +1,277 @@
...
+}
+
+#' @rdname plot_
+#' @importFrom manynet autographr
+#' @importFrom dplyr %>% select mutate distinct filter rename
+#' @return A plot of agreements' lineages.
+#' @examples
+#' \donttest{
+#' #lineage <- dplyr::filter(manyenviron::agreements$HUGGO, Beg > "2000-01-01",
+#' #Beg < "2001-12-31")
```
Comment (jaeltan) [inline R/plot.R:104]: Begin instead of Beg

File: R/plot.R [hunk 18]
```diff
@@ -0,0 +1,277 @@
...
+#' Available themes are "light", "dark", and "earth".
+#' @details `plot_map()` creates a plot of the a unimodal geographical network 
+#' at a single point in time.
+#' @importFrom manynet is_graph is_multiplex as_edgelist as_tidygraph node_names
+#' @importFrom dplyr mutate inner_join rename filter
+#' @return A map of a country level geographical network.
+#' @examples
+#' \donttest{
+#' #memberships <- dplyr::filter(manyenviron::memberships$ECOLEX_MEM,
+#' #Beg > "2000-01-01" & Beg < "2000-12-12")
```
Comment (jaeltan) [inline R/plot.R:153]: Begin instead of Beg

File: R/plot.R [hunk 19]
```diff
@@ -0,0 +1,277 @@
...
+#' #plot_map(memberships, actor = "stateID") +
+#' #ggplot2::labs(title = "Bilateral International Environmental Treaties Signed in the year 2000",
+#' #subtitle = "Ecolex data")
+#'}
+#' @export
+plot_map <- function(dataset, actor = "StateID", treaty_type = NULL,
```
Comment (jaeltan) [inline R/plot.R:159]: stateID instead of StateID

File: tests/testthat/test_compare.R [hunk 20]
```diff
@@ -0,0 +1,63 @@
...
+  expect_type(db, "list")
+  expect_length(db, 9)
+  expect_true(ggplot2::is.ggplot(db))
+  expect_named(db, c("data", "layers", "scales", "mapping", "theme",
+                     "coordinates", "facet", "plot_env", "labels"))
+})
+
+test_that("compare_categories() returns the correct output format", {
+  db <- compare_categories(database = emperors, key = "ID")
+  db1 <- compare_categories(database = emperors, key = "ID", variable = "Beg")
```
Comment (jaeltan) [inline tests/testthat/test_compare.R:14]: Do we need to change 'Beg' in the emperors database to 'Begin' too?

**Review by jaeltan — CHANGES_REQUESTED** [review]
Just some minor labelling issues, thanks @henriquesposito

File: tests/testthat/test_compare.R (hunk 20 above)
Comment (henriquesposito) [reply tests/testthat/test_compare.R:14]: Good catch, will do so!

**Review by jaeltan — COMMENTED** [review]
Thanks @henriquesposito , I just have some clarifications to make about `compare_ranges()` before I add the cheatsheet

File: R/compare.R [hunk 21]
```diff
@@ -0,0 +1,462 @@
...
+             max(y, na.rm = TRUE), NA)
+    })), na.rm = TRUE))
+    cbind(Observations, Variables, Earliest_Date, Latest_Date)
+  }))
+  dplyr::as_tibble(cbind(names, out))
+}
+
+#' Compare variable ranges for 'many' data
+#'
+#' @details `compare_ranges()` compares the number of observations, variables,
```
[the remark this answers is not in the document]
Comment (henriquesposito) [reply R/compare.R:47]: Yeah, ideally they should be but since the columns (i.e. "min") display several values some of which might not be dates, they are all converted to "character". I am not sure how to display this information differently for now, however.

**Review by jaeltan — APPROVED** [review]
