### PR TITLE
v0.9.1

### LINKED ISSUE #266: Add startup messages for 'many packages'
Add a startup message for data packages not on CRAN that works when users load packages (`library()`).

These can include a link to the vignette or the website to help users, if they need help.

### LINKED ISSUE #267: Add links to output message in console
For `get_packages()` and the compare functions...

See https://github.com/rstudio/rstudio/issues/1941 and https://github.com/rstudio/rstudio/issues/2530 and https://github.com/r-lib/testthat/pull/1544

### LINKED ISSUE #282: Change all mentions from 'database' to 'datacube' across all packages

### LINKED ISSUE #293: Bug with `consolidate()` function when resolving multiple 'mdate' variables differently
```r
dat1 <- dplyr::tibble(manyID = c("NZL", "BRA", "CHF"),
                      date = messydates::as_messydate(c("1990-01-01",
                                                        "1990-01-02",
                                                        "1990-01-01:1990-01-31")),
                      number = c(100, 1000, 10000))
dat2 <- dplyr::tibble(manyID = c("NZL", "BRA"),
                      date = messydates::as_messydate(c("1990-01-01",
                                                        "1990-01-03")))
dat3 <- dplyr::tibble(manyID = c("NZL", "BRA", "CHF", "OTH"),
                      date = messydates::as_messydate(c("1990-01-01",
                                                        "1990-01-02",
                                                        "1990-01-01:1990-01-31",
                                                        NA)),
                      number = c(100, 1200, 12222, 21))
test2 <- list(a = dat1, b = dat2, c = dat3)
consolidate(test2, "any", "any", resolve = c(date = "min", number = "max"))
consolidate(test2, "every", "any", resolve = c(date = "mean", number = "median"))
```

These issues appear to have appeared since the latest changes we made to `{messydates}`, but they appear here.

### LINKED ISSUE #294: Bug with `call_sources()` function
```r
call_sources("manydata", "emperors") # works
call_sources("manyenviron", "agreements") # does not work
```
This should not be the case since the information extracted from the datacube documentation should be similar.

### PR DESCRIPTION
**Pull request by henriquesposito**
# Description

This patch fixes compatibility issues with the new version of `{ggplot2}`.

## Package

* Updated test expectations to make package compatible with the new release of `{ggplot2}`

## Connection

* Closed #266 by adding startup messages to 'many' packages
* Closed #267 by adding links to package websites in console messages
* Closed #282 by updating all references from 'database' to 'datacube'
* Closed #293 by fixing bugs related to missing dates when using `consolidate()`
* Closed #294 by updating how `call_sources()` identify datasets within datacubes

# Checklist:

- [x] PR form
  - [x] I have given this pull request an informative title
  - [x] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [x] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [x] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [x] Package builds on Mac
  - [x] Package builds on Windows
  - [x] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
  - [ ] CodeFactor check: Package improves or maintains good style
- [x] Documentation
  - [x] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [x] Any longer functions are commented inline so that it is easier to debug in the future
  - [x] PR description above and the NEWS.md file are aligned
  - [x] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

### CODE REVIEW

File: R/compare.R [hunk 1]
```diff
@@ -469,3 +469,49 @@ plot.compare_categories <- function(x, ...) {
...
 }
+
+#' #' Compare similarities and differences in treaties from 'many' datasets
+#' #' 
+#' #' @details Certain datasets, or consolidated datacubes, in 'many' packages
+#' #' contains information on treaties which can be compared with 
+#' #' `compare_treaties()`.
+#' #' @family compare_
+#' #' @param dataset A dataset in a datacube from one of the many packages.
+#' #' @param text_variable Text variable.
```
Comment (jaeltan) [inline R/compare.R:480]: Are we adding the Text variable back to the datasets? Currently none of the datasets have the text stored in them

**Review by jaeltan — APPROVED** [review]
Thanks for the work @henriquesposito , nothing major on my side, just a question about compare_treaties().

File: R/compare.R (hunk 1 above)
Comment (henriquesposito) [reply R/compare.R:480]: This was just a reference/placeholder for the future, it will likely change. I will remove it for now to avoid confusion. Thank you.
